---
- name: Check if chrony package is installed
  hosts: ubuntu_nodes
  become: yes
  tasks:
    - name: Gather installed package facts
      ansible.builtin.package_facts:

    - name: Check if chrony package is installed
      debug:
        msg: "Chrony is installed"
      when: "'chrony' in ansible_facts.packages"

    - name: Notify if chrony package is not installed
      debug:
        msg: "Chrony is NOT installed"
      when: "'chrony' not in ansible_facts.packages"

