---
- name: Install chrony package on Ubuntu nodes
  apt:
    name: chrony
    state: present
  when: ansible_os_family == "Ubuntu"

- name: Start and enable chrony service
  service:
    name: chrony
    state: started
    enabled: yes
