---
- name: Install chrony package on Ubuntu nodes
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure chrony package is installed
      apt:
        name: chrony
        state: present

    - name: Start and enable chrony service
      service:
        name: chrony
        state: started
        enabled: yes
